---
- hosts: all
  gather_facts: no

  tasks:
    - name: Create security group
      os_security_group:  
        name: "{{ group_name }}"
        state: present
        description: "{{ group_description }}"

    - name: Add security rules 
      os_security_group_rule:
        security_group: "{{ group_name }}"
        protocol: "{{ item.value.protocol }}"
        port_range_min: "{{ item.value.port_range_min }}"
        port_range_max: "{{ item.value.port_range_max }}"
        remote_ip_prefix: "{{ item.value.remote_ip_prefix }}"
      loop: "{{ ports | dict2items }}"

